package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevUse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevUse extends BaseOmDevUse<OmDevUse> {
	public static final OmDevUse dao = new OmDevUse();
}
