package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevChangeEntity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevChangeEntity extends BaseOmDevChangeEntity<OmDevChangeEntity> {
	public static final OmDevChangeEntity dao = new OmDevChangeEntity();
}
