package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevTransferDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevTransferDetail extends BaseOmDevTransferDetail<OmDevTransferDetail> {
	public static final OmDevTransferDetail dao = new OmDevTransferDetail();
}
