package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevTransferOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevTransferOrder extends BaseOmDevTransferOrder<OmDevTransferOrder> {
	public static final OmDevTransferOrder dao = new OmDevTransferOrder();
}
