package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevTransferEntity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevTransferEntity extends BaseOmDevTransferEntity<OmDevTransferEntity> {
	public static final OmDevTransferEntity dao = new OmDevTransferEntity();
}
