package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmDevChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmDevChange extends BaseOmDevChange<OmDevChange> {
	public static final OmDevChange dao = new OmDevChange();
}
