package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmSuppliesChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmSuppliesChange extends BaseOmSuppliesChange<OmSuppliesChange> {
	public static final OmSuppliesChange dao = new OmSuppliesChange();
}
