package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BaseOmSuppliesUse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmSuppliesUse extends BaseOmSuppliesUse<OmSuppliesUse> {
	public static final OmSuppliesUse dao = new OmSuppliesUse();
}
