package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmChangeReason;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmChangeReason extends BasePmChangeReason<PmChangeReason> {
	public static final PmChangeReason dao = new PmChangeReason();
}
