package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmChangeEventReason;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmChangeEventReason extends BasePmChangeEventReason<PmChangeEventReason> {
	public static final PmChangeEventReason dao = new PmChangeEventReason();
}
