package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmChangeEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmChangeEvent extends BasePmChangeEvent<PmChangeEvent> {
	public static final PmChangeEvent dao = new PmChangeEvent();
}
