package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmDevPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmDevPage extends BasePmDevPage<PmDevPage> {
	public static final PmDevPage dao = new PmDevPage();
}
