package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmDevStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmDevStock extends BasePmDevStock<PmDevStock> {
	public static final PmDevStock dao = new PmDevStock();
}
