package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmDevButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmDevButton extends BasePmDevButton<PmDevButton> {
	public static final PmDevButton dao = new PmDevButton();
}
