package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmEquipmentClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmEquipmentClass extends BasePmEquipmentClass<PmEquipmentClass> {
	public static final PmEquipmentClass dao = new PmEquipmentClass();
}
