package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmEquipmentType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmEquipmentType extends BasePmEquipmentType<PmEquipmentType> {
	public static final PmEquipmentType dao = new PmEquipmentType();
}
