package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmEquipmentStockWarn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmEquipmentStockWarn extends BasePmEquipmentStockWarn<PmEquipmentStockWarn> {
	public static final PmEquipmentStockWarn dao = new PmEquipmentStockWarn();
}
