package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmEquipmentState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmEquipmentState extends BasePmEquipmentState<PmEquipmentState> {
	public static final PmEquipmentState dao = new PmEquipmentState();
}
