package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmManufacturer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmManufacturer extends BasePmManufacturer<PmManufacturer> {
	public static final PmManufacturer dao = new PmManufacturer();
}
