package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmMobox;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmMobox extends BasePmMobox<PmMobox> {
	public static final PmMobox dao = new PmMobox();
}
