package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmModemClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmModemClass extends BasePmModemClass<PmModemClass> {
	public static final PmModemClass dao = new PmModemClass();
}
