package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmModem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmModem extends BasePmModem<PmModem> {
	public static final PmModem dao = new PmModem();
}
