package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmStaffDepot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmStaffDepot extends BasePmStaffDepot<PmStaffDepot> {
	public static final PmStaffDepot dao = new PmStaffDepot();
}
