package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmStaffButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmStaffButton extends BasePmStaffButton<PmStaffButton> {
	public static final PmStaffButton dao = new PmStaffButton();
}
