package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmStaffPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmStaffPage extends BasePmStaffPage<PmStaffPage> {
	public static final PmStaffPage dao = new PmStaffPage();
}
