package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmSuppliesUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmSuppliesUnit extends BasePmSuppliesUnit<PmSuppliesUnit> {
	public static final PmSuppliesUnit dao = new PmSuppliesUnit();
}
