package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmSuppliesStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmSuppliesStock extends BasePmSuppliesStock<PmSuppliesStock> {
	public static final PmSuppliesStock dao = new PmSuppliesStock();
}
