package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmSuppliesClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmSuppliesClass extends BasePmSuppliesClass<PmSuppliesClass> {
	public static final PmSuppliesClass dao = new PmSuppliesClass();
}
