package com.ztesoft.terminal.common.model;

import com.ztesoft.terminal.common.model.base.BasePmSuppliesStockWarn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmSuppliesStockWarn extends BasePmSuppliesStockWarn<PmSuppliesStockWarn> {
	public static final PmSuppliesStockWarn dao = new PmSuppliesStockWarn();
}
