package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmSuppliesUnit<M extends BasePmSuppliesUnit<M>> extends Model<M> implements IBean {

	public void setUnitCode(java.lang.String unitCode) {
		set("UNIT_CODE", unitCode);
	}

	public java.lang.String getUnitCode() {
		return get("UNIT_CODE");
	}

	public void setUnitName(java.lang.String unitName) {
		set("UNIT_NAME", unitName);
	}

	public java.lang.String getUnitName() {
		return get("UNIT_NAME");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

}
