package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmStaffDepot<M extends BasePmStaffDepot<M>> extends Model<M> implements IBean {

	public void setStaffId(java.math.BigDecimal staffId) {
		set("STAFF_ID", staffId);
	}

	public java.math.BigDecimal getStaffId() {
		return get("STAFF_ID");
	}

	public void setDepotCode(java.lang.String depotCode) {
		set("DEPOT_CODE", depotCode);
	}

	public java.lang.String getDepotCode() {
		return get("DEPOT_CODE");
	}

}
