package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmDevPage<M extends BasePmDevPage<M>> extends Model<M> implements IBean {

	public void setPageCode(java.lang.String pageCode) {
		set("PAGE_CODE", pageCode);
	}

	public java.lang.String getPageCode() {
		return get("PAGE_CODE");
	}

	public void setPageName(java.lang.String pageName) {
		set("PAGE_NAME", pageName);
	}

	public java.lang.String getPageName() {
		return get("PAGE_NAME");
	}

}
