package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmMobox<M extends BasePmMobox<M>> extends Model<M> implements IBean {

	public void setSn(java.lang.String sn) {
		set("SN", sn);
	}

	public java.lang.String getSn() {
		return get("SN");
	}

	public void setManufacturerCode(java.lang.String manufacturerCode) {
		set("MANUFACTURER_CODE", manufacturerCode);
	}

	public java.lang.String getManufacturerCode() {
		return get("MANUFACTURER_CODE");
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		set("EQUIPMENT_TYPE", equipmentType);
	}

	public java.lang.String getEquipmentType() {
		return get("EQUIPMENT_TYPE");
	}

	public void setEquipmentState(java.lang.String equipmentState) {
		set("EQUIPMENT_STATE", equipmentState);
	}

	public java.lang.String getEquipmentState() {
		return get("EQUIPMENT_STATE");
	}

	public void setDepotCode(java.lang.String depotCode) {
		set("DEPOT_CODE", depotCode);
	}

	public java.lang.String getDepotCode() {
		return get("DEPOT_CODE");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setWorkOrderCode(java.lang.String workOrderCode) {
		set("WORK_ORDER_CODE", workOrderCode);
	}

	public java.lang.String getWorkOrderCode() {
		return get("WORK_ORDER_CODE");
	}

	public void setUseDate(java.util.Date useDate) {
		set("USE_DATE", useDate);
	}

	public java.util.Date getUseDate() {
		return get("USE_DATE");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setUseManName(java.lang.String useManName) {
		set("USE_MAN_NAME", useManName);
	}

	public java.lang.String getUseManName() {
		return get("USE_MAN_NAME");
	}

	public void setCustName(java.lang.String custName) {
		set("CUST_NAME", custName);
	}

	public java.lang.String getCustName() {
		return get("CUST_NAME");
	}

}
