package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmDevTransferOrder<M extends BaseOmDevTransferOrder<M>> extends Model<M> implements IBean {

	public void setTransferCode(java.lang.String transferCode) {
		set("TRANSFER_CODE", transferCode);
	}

	public java.lang.String getTransferCode() {
		return get("TRANSFER_CODE");
	}

	public void setTransferTitle(java.lang.String transferTitle) {
		set("TRANSFER_TITLE", transferTitle);
	}

	public java.lang.String getTransferTitle() {
		return get("TRANSFER_TITLE");
	}

	public void setInDepotCode(java.lang.String inDepotCode) {
		set("IN_DEPOT_CODE", inDepotCode);
	}

	public java.lang.String getInDepotCode() {
		return get("IN_DEPOT_CODE");
	}

	public void setOutDepotCode(java.lang.String outDepotCode) {
		set("OUT_DEPOT_CODE", outDepotCode);
	}

	public java.lang.String getOutDepotCode() {
		return get("OUT_DEPOT_CODE");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}

	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

	public void setOperatorDate(java.util.Date operatorDate) {
		set("OPERATOR_DATE", operatorDate);
	}

	public java.util.Date getOperatorDate() {
		return get("OPERATOR_DATE");
	}

	public void setOperatorName(java.lang.String operatorName) {
		set("OPERATOR_NAME", operatorName);
	}

	public java.lang.String getOperatorName() {
		return get("OPERATOR_NAME");
	}

	public void setOperatorId(java.math.BigDecimal operatorId) {
		set("OPERATOR_ID", operatorId);
	}

	public java.math.BigDecimal getOperatorId() {
		return get("OPERATOR_ID");
	}

	public void setComments(java.lang.String comments) {
		set("COMMENTS", comments);
	}

	public java.lang.String getComments() {
		return get("COMMENTS");
	}

}
