package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmChangeEventReason<M extends BasePmChangeEventReason<M>> extends Model<M> implements IBean {

	public void setEventCode(java.lang.String eventCode) {
		set("EVENT_CODE", eventCode);
	}

	public java.lang.String getEventCode() {
		return get("EVENT_CODE");
	}

	public void setReasonCode(java.lang.String reasonCode) {
		set("REASON_CODE", reasonCode);
	}

	public java.lang.String getReasonCode() {
		return get("REASON_CODE");
	}

}
