package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmStaffButton<M extends BasePmStaffButton<M>> extends Model<M> implements IBean {

	public void setStaffId(java.math.BigDecimal staffId) {
		set("STAFF_ID", staffId);
	}

	public java.math.BigDecimal getStaffId() {
		return get("STAFF_ID");
	}

	public void setButtonCode(java.lang.String buttonCode) {
		set("BUTTON_CODE", buttonCode);
	}

	public java.lang.String getButtonCode() {
		return get("BUTTON_CODE");
	}

}
