package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmEquipmentClass<M extends BasePmEquipmentClass<M>> extends Model<M> implements IBean {

	public void setClassCode(java.lang.String classCode) {
		set("CLASS_CODE", classCode);
	}

	public java.lang.String getClassCode() {
		return get("CLASS_CODE");
	}

	public void setClassName(java.lang.String className) {
		set("CLASS_NAME", className);
	}

	public java.lang.String getClassName() {
		return get("CLASS_NAME");
	}

	public void setIsManageSn(java.math.BigDecimal isManageSn) {
		set("IS_MANAGE_SN", isManageSn);
	}

	public java.math.BigDecimal getIsManageSn() {
		return get("IS_MANAGE_SN");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

}
