package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmDevButton<M extends BasePmDevButton<M>> extends Model<M> implements IBean {

	public void setButtonCode(java.lang.String buttonCode) {
		set("BUTTON_CODE", buttonCode);
	}

	public java.lang.String getButtonCode() {
		return get("BUTTON_CODE");
	}

	public void setButtonName(java.lang.String buttonName) {
		set("BUTTON_NAME", buttonName);
	}

	public java.lang.String getButtonName() {
		return get("BUTTON_NAME");
	}

}
