package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmDevTransferDetail<M extends BaseOmDevTransferDetail<M>> extends Model<M> implements IBean {

	public void setTransferDetailId(java.math.BigDecimal transferDetailId) {
		set("TRANSFER_DETAIL_ID", transferDetailId);
	}

	public java.math.BigDecimal getTransferDetailId() {
		return get("TRANSFER_DETAIL_ID");
	}

	public void setTransferCode(java.lang.String transferCode) {
		set("TRANSFER_CODE", transferCode);
	}

	public java.lang.String getTransferCode() {
		return get("TRANSFER_CODE");
	}

	public void setChangeId(java.math.BigDecimal changeId) {
		set("CHANGE_ID", changeId);
	}

	public java.math.BigDecimal getChangeId() {
		return get("CHANGE_ID");
	}

	public void setEquipmentClass(java.lang.String equipmentClass) {
		set("EQUIPMENT_CLASS", equipmentClass);
	}

	public java.lang.String getEquipmentClass() {
		return get("EQUIPMENT_CLASS");
	}

	public void setManufacturerCode(java.lang.String manufacturerCode) {
		set("MANUFACTURER_CODE", manufacturerCode);
	}

	public java.lang.String getManufacturerCode() {
		return get("MANUFACTURER_CODE");
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		set("EQUIPMENT_TYPE", equipmentType);
	}

	public java.lang.String getEquipmentType() {
		return get("EQUIPMENT_TYPE");
	}

	public void setNum(java.math.BigDecimal num) {
		set("NUM", num);
	}

	public java.math.BigDecimal getNum() {
		return get("NUM");
	}

}
