package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmChangeEvent<M extends BasePmChangeEvent<M>> extends Model<M> implements IBean {

	public void setEventCode(java.lang.String eventCode) {
		set("EVENT_CODE", eventCode);
	}

	public java.lang.String getEventCode() {
		return get("EVENT_CODE");
	}

	public void setEventName(java.lang.String eventName) {
		set("EVENT_NAME", eventName);
	}

	public java.lang.String getEventName() {
		return get("EVENT_NAME");
	}

	public void setOldState(java.lang.String oldState) {
		set("OLD_STATE", oldState);
	}

	public java.lang.String getOldState() {
		return get("OLD_STATE");
	}

	public void setNewState(java.lang.String newState) {
		set("NEW_STATE", newState);
	}

	public java.lang.String getNewState() {
		return get("NEW_STATE");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

}
