package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmModem<M extends BasePmModem<M>> extends Model<M> implements IBean {

	public void setSn(java.lang.String sn) {
		set("SN", sn);
	}

	public java.lang.String getSn() {
		return get("SN");
	}

	public void setLoid(java.lang.String loid) {
		set("LOID", loid);
	}

	public java.lang.String getLoid() {
		return get("LOID");
	}

	public void setIp(java.lang.String ip) {
		set("IP", ip);
	}

	public java.lang.String getIp() {
		return get("IP");
	}

	public void setMac(java.lang.String mac) {
		set("MAC", mac);
	}

	public java.lang.String getMac() {
		return get("MAC");
	}

	public void setManufacturerCode(java.lang.String manufacturerCode) {
		set("MANUFACTURER_CODE", manufacturerCode);
	}

	public java.lang.String getManufacturerCode() {
		return get("MANUFACTURER_CODE");
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		set("EQUIPMENT_TYPE", equipmentType);
	}

	public java.lang.String getEquipmentType() {
		return get("EQUIPMENT_TYPE");
	}

	public void setModemClass(java.lang.String modemClass) {
		set("MODEM_CLASS", modemClass);
	}

	public java.lang.String getModemClass() {
		return get("MODEM_CLASS");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

	public void setDepotCode(java.lang.String depotCode) {
		set("DEPOT_CODE", depotCode);
	}

	public java.lang.String getDepotCode() {
		return get("DEPOT_CODE");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setStateDate(java.util.Date stateDate) {
		set("STATE_DATE", stateDate);
	}

	public java.util.Date getStateDate() {
		return get("STATE_DATE");
	}

	public void setIsOld(java.math.BigDecimal isOld) {
		set("IS_OLD", isOld);
	}

	public java.math.BigDecimal getIsOld() {
		return get("IS_OLD");
	}

	public void setBatchId(java.math.BigDecimal batchId) {
		set("BATCH_ID", batchId);
	}

	public java.math.BigDecimal getBatchId() {
		return get("BATCH_ID");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setCustName(java.lang.String custName) {
		set("CUST_NAME", custName);
	}

	public java.lang.String getCustName() {
		return get("CUST_NAME");
	}

	public void setCustTel(java.lang.String custTel) {
		set("CUST_TEL", custTel);
	}

	public java.lang.String getCustTel() {
		return get("CUST_TEL");
	}

	public void setAccount(java.lang.String account) {
		set("ACCOUNT", account);
	}

	public java.lang.String getAccount() {
		return get("ACCOUNT");
	}

	public void setWorkOrderCode(java.lang.String workOrderCode) {
		set("WORK_ORDER_CODE", workOrderCode);
	}

	public java.lang.String getWorkOrderCode() {
		return get("WORK_ORDER_CODE");
	}

	public void setUseDate(java.util.Date useDate) {
		set("USE_DATE", useDate);
	}

	public java.util.Date getUseDate() {
		return get("USE_DATE");
	}

	public void setUseManName(java.lang.String useManName) {
		set("USE_MAN_NAME", useManName);
	}

	public java.lang.String getUseManName() {
		return get("USE_MAN_NAME");
	}

}
