package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmDevTransferEntity<M extends BaseOmDevTransferEntity<M>> extends Model<M> implements IBean {

	public void setTransferDetailId(java.math.BigDecimal transferDetailId) {
		set("TRANSFER_DETAIL_ID", transferDetailId);
	}

	public java.math.BigDecimal getTransferDetailId() {
		return get("TRANSFER_DETAIL_ID");
	}

	public void setSnNo(java.lang.String snNo) {
		set("SN_NO", snNo);
	}

	public java.lang.String getSnNo() {
		return get("SN_NO");
	}

}
