package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmSuppliesChange<M extends BaseOmSuppliesChange<M>> extends Model<M> implements IBean {

	public void setChangeId(java.math.BigDecimal changeId) {
		set("CHANGE_ID", changeId);
	}

	public java.math.BigDecimal getChangeId() {
		return get("CHANGE_ID");
	}

	public void setDepotCode(java.lang.String depotCode) {
		set("DEPOT_CODE", depotCode);
	}

	public java.lang.String getDepotCode() {
		return get("DEPOT_CODE");
	}

	public void setSuppliesClass(java.lang.String suppliesClass) {
		set("SUPPLIES_CLASS", suppliesClass);
	}

	public java.lang.String getSuppliesClass() {
		return get("SUPPLIES_CLASS");
	}

	public void setChangeEvent(java.lang.String changeEvent) {
		set("CHANGE_EVENT", changeEvent);
	}

	public java.lang.String getChangeEvent() {
		return get("CHANGE_EVENT");
	}

	public void setChangeReason(java.lang.String changeReason) {
		set("CHANGE_REASON", changeReason);
	}

	public java.lang.String getChangeReason() {
		return get("CHANGE_REASON");
	}

	public void setNum(java.math.BigDecimal num) {
		set("NUM", num);
	}

	public java.math.BigDecimal getNum() {
		return get("NUM");
	}

	public void setOperatorName(java.lang.String operatorName) {
		set("OPERATOR_NAME", operatorName);
	}

	public java.lang.String getOperatorName() {
		return get("OPERATOR_NAME");
	}

	public void setOperatorDate(java.util.Date operatorDate) {
		set("OPERATOR_DATE", operatorDate);
	}

	public java.util.Date getOperatorDate() {
		return get("OPERATOR_DATE");
	}

	public void setComments(java.lang.String comments) {
		set("COMMENTS", comments);
	}

	public java.lang.String getComments() {
		return get("COMMENTS");
	}

}
