package com.ztesoft.terminal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmManufacturer<M extends BasePmManufacturer<M>> extends Model<M> implements IBean {

	public void setManufacturerCode(java.lang.String manufacturerCode) {
		set("MANUFACTURER_CODE", manufacturerCode);
	}

	public java.lang.String getManufacturerCode() {
		return get("MANUFACTURER_CODE");
	}

	public void setManufacturerName(java.lang.String manufacturerName) {
		set("MANUFACTURER_NAME", manufacturerName);
	}

	public java.lang.String getManufacturerName() {
		return get("MANUFACTURER_NAME");
	}

	public void setState(java.lang.String state) {
		set("STATE", state);
	}

	public java.lang.String getState() {
		return get("STATE");
	}

}
